{{- if and .Values.postgresql.enabled .Values.backup.enabled (not .Values.backup.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgvector.backup.secretName" . }}
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ required "backup.s3.accessKey must be set when backup is enabled without an existing secret" .Values.backup.s3.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "backup.s3.secretKey must be set when backup is enabled without an existing secret" .Values.backup.s3.secretKey | quote }}
{{- end }}

