{{- if and .Values.postgresql.enabled .Values.backup.enabled }}
{{- $bucket := required "backup.s3.bucket must be provided when backups are enabled" .Values.backup.s3.bucket -}}
{{- $region := required "backup.s3.region must be provided when backups are enabled" .Values.backup.s3.region -}}
{{- $secretName := default (include "pgvector.backup.secretName" .) .Values.backup.s3.existingSecret -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pgvector.fullname" . }}-backup
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  {{- $annotations := include "pgvector.annotations" (dict "global" $.Values.annotations "component" .Values.backup.annotations) | fromYaml -}}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.backup.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.backup.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "pgvector.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: backup
          {{- $annotations := include "pgvector.annotations" (dict "global" $.Values.annotations "component" .Values.backup.podAnnotations) | fromYaml -}}
          {{- with $annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "pgvector.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
            - name: pg-backup
              image: {{ .Values.backup.image.registry }}/{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}
              imagePullPolicy: {{ .Values.backup.image.pullPolicy }}
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "pgvector.postgresql.secretName" . }}
                      key: postgres-password
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "pgvector.postgresql.secretName" . }}
                      key: postgres-user
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "pgvector.postgresql.secretName" . }}
                      key: postgres-database
                - name: PGHOST
                  value: {{ include "pgvector.fullname" . }}-postgresql-master.{{ .Release.Namespace }}.svc.cluster.local
                - name: PGPORT
                  value: "5432"
                - name: AWS_REGION
                  value: {{ $region | quote }}
                - name: S3_BUCKET
                  value: {{ $bucket | quote }}
                - name: S3_PREFIX
                  value: {{ .Values.backup.s3.prefix | default "" | quote }}
                - name: AWS_S3_FORCE_PATH_STYLE
                  value: {{ ternary "true" "false" .Values.backup.s3.usePathStyle | quote }}
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ $secretName }}
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ $secretName }}
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINT
                  value: {{ .Values.backup.s3.endpoint | quote }}
                - name: RETENTION_DAYS
                  value: {{ printf "%d" .Values.backup.retentionDays | quote }}
                - name: PG_DUMP_FORMAT
                  value: {{ .Values.backup.pgDumpFormat | quote }}
                - name: COMPRESS
                  value: {{ ternary "true" "false" .Values.backup.compress | quote }}
                - name: POSTGRES_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "pgvector.postgresql.secretName" . }}
                      key: postgres-url
{{- range .Values.backup.env }}
                - name: {{ .name }}
                  {{- if hasKey . "value" }}
                  value: {{ .value | quote }}
                  {{- end }}
                  {{- if .valueFrom }}
                  valueFrom:
{{ toYaml .valueFrom | nindent 18 }}
                  {{- end }}
{{- end }}
              command:
                - /bin/bash
                - -c
                - |
                  set -euo pipefail

                  if ! command -v pg_dump &>/dev/null; then
                    echo "Installing pg_dump utilities..."
                    install_packages postgresql-client
                  fi

                  if ! command -v aws &>/dev/null; then
                    echo "Installing awscli..."
                    install_packages awscli
                  fi

                  export PGPASSWORD PGUSER PGDATABASE PGHOST PGPORT
                  export AWS_REGION AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY

                  TIMESTAMP="$(date -u +'%Y%m%d%H%M%S')"
                  DB_NAME="${PGDATABASE:-postgres}"
                  FILE_BASENAME="${DB_NAME}_${TIMESTAMP}.dump"
                  BACKUP_PATH="/tmp/${FILE_BASENAME}"

                  echo "Creating PostgreSQL backup ${BACKUP_PATH}"
                  if [ -n "${POSTGRES_URL}" ]; then
                    pg_dump --format="${PG_DUMP_FORMAT}" "${POSTGRES_URL}" --file="${BACKUP_PATH}"
                  else
                    pg_dump --format="${PG_DUMP_FORMAT}" --host="${PGHOST}" --port="${PGPORT}" --username="${PGUSER}" "${PGDATABASE}" --file="${BACKUP_PATH}"
                  fi

                  if [ "${COMPRESS}" = "true" ]; then
                    gzip "${BACKUP_PATH}"
                    BACKUP_PATH="${BACKUP_PATH}.gz"
                  fi

                  DEST_PREFIX="${S3_PREFIX%/}"
                  if [ -n "${DEST_PREFIX}" ]; then
                    DEST_URI="s3://${S3_BUCKET}/${DEST_PREFIX}/$(basename "${BACKUP_PATH}")"
                  else
                    DEST_URI="s3://${S3_BUCKET}/$(basename "${BACKUP_PATH}")"
                  fi

                  AWS_ARGS=(--region "${AWS_REGION}")
                  if [ -n "${AWS_ENDPOINT}" ]; then
                    AWS_ARGS+=(--endpoint-url "${AWS_ENDPOINT}")
                  fi

                  if [ "${AWS_S3_FORCE_PATH_STYLE}" = "true" ]; then
                    export AWS_S3_FORCE_PATH_STYLE=true
                  fi

                  echo "Uploading backup to ${DEST_URI}"
                  aws "${AWS_ARGS[@]}" s3 cp "${BACKUP_PATH}" "${DEST_URI}"

                  if [ "${RETENTION_DAYS}" -gt 0 ]; then
                    CUTOFF="$(date -u -d "-${RETENTION_DAYS} days" +%s)"
                    LIST_URI="s3://${S3_BUCKET}/"
                    if [ -n "${DEST_PREFIX}" ]; then
                      LIST_URI="s3://${S3_BUCKET}/${DEST_PREFIX}/"
                    fi
                    echo "Pruning backups older than ${RETENTION_DAYS} days"
                    aws "${AWS_ARGS[@]}" s3 ls "${LIST_URI}" | while read -r DATE TIME SIZE KEY; do
                      [ -z "${DATE}" ] && continue
                      if [ "${DATE}" = "PRE" ]; then
                        continue
                      fi
                      TS="$(date -d "${DATE} ${TIME}" +%s)"
                      if [ "${TS}" -lt "${CUTOFF}" ]; then
                        echo "Removing s3://${S3_BUCKET}/${KEY}"
                        aws "${AWS_ARGS[@]}" s3 rm "s3://${S3_BUCKET}/${KEY}"
                      fi
                    done
                  fi

                  echo "Backup completed successfully."
              resources:
                {{- toYaml .Values.backup.resources | nindent 16 }}
          {{- with .Values.backup.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backup.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backup.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}

