{{- if and .Values.networkPolicy.enabled .Values.postgresql.enabled }}
{{- $root := . -}}
{{- $allowNamespaces := default (list) .Values.networkPolicy.allowNamespaces -}}
{{- $allowCIDRs := default (list) .Values.networkPolicy.allowCIDRs -}}
{{- $extraIngress := default (list) .Values.networkPolicy.extraIngress -}}
{{- $extraEgress := default (list) .Values.networkPolicy.extraEgress -}}
{{- $components := list
  (dict "name" "postgresql-master" "enabled" true "component" "postgresql-master")
  (dict "name" "postgresql-replica" "enabled" (gt (int .Values.postgresql.replica.replicaCount) 0) "component" "postgresql-replica")
  (dict "name" "pgbouncer" "enabled" .Values.postgresql.pgbouncer.enabled "component" "pgbouncer")
  (dict "name" "haproxy" "enabled" .Values.postgresql.haproxy.enabled "component" "haproxy")
-}}
{{- range $components }}
{{- if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pgvector.fullname" $root }}-{{ .name }}-np
  labels:
    {{- include "pgvector.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}-networkpolicy
spec:
  podSelector:
    matchLabels:
      {{- include "pgvector.selectorLabels" $root | nindent 6 }}
      app.kubernetes.io/component: {{ .component }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
        {{- range $allowNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
        {{- range $allowCIDRs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
  {{- range $extraIngress }}
    - {{ toYaml . | nindent 6 }}
  {{- end }}
  egress:
    - {}
  {{- range $extraEgress }}
    - {{ toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

