{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgvector.postgresql.secretName" . }}
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql-secret
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.postgresPassword | default (include "pgvector.postgresql.password" .) | quote }}
  postgres-user: {{ .Values.postgresql.postgresUser | quote }}
  postgres-database: {{ .Values.postgresql.postgresDatabase | quote }}
  postgres-host: {{ include "pgvector.fullname" . }}-postgresql-master.{{ .Release.Namespace }}.svc.cluster.local
  postgres-port: "5432"
  postgres-url: {{ include "pgvector.postgresql.connectionString" . | quote }}
  replica-host: {{ include "pgvector.fullname" . }}-postgresql-replica.{{ .Release.Namespace }}.svc.cluster.local
  replica-port: "5432"
  replica-url: postgresql://{{ .Values.postgresql.postgresUser }}:{{ .Values.postgresql.postgresPassword | default (include "pgvector.postgresql.password" .) }}@{{ include "pgvector.fullname" . }}-postgresql-replica.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgresql.postgresDatabase }}?sslmode=disable
{{- if .Values.postgresql.pgbouncer.enabled }}
  pgbouncer-host: {{ include "pgvector.fullname" . }}-pgbouncer.{{ .Release.Namespace }}.svc.cluster.local
  pgbouncer-port: "{{ .Values.postgresql.pgbouncer.service.port }}"
  pgbouncer-url: postgresql://{{ .Values.postgresql.postgresUser }}:{{ .Values.postgresql.postgresPassword | default (include "pgvector.postgresql.password" .) }}@{{ include "pgvector.fullname" . }}-pgbouncer.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.postgresql.pgbouncer.service.port }}/{{ .Values.postgresql.postgresDatabase }}?sslmode=disable
{{- end }}
{{- if .Values.postgresql.haproxy.enabled }}
  haproxy-host: {{ include "pgvector.fullname" . }}-haproxy.{{ .Release.Namespace }}.svc.cluster.local
  haproxy-port: "{{ .Values.postgresql.haproxy.service.port }}"
  haproxy-url: postgresql://{{ .Values.postgresql.postgresUser }}:{{ .Values.postgresql.postgresPassword | default (include "pgvector.postgresql.password" .) }}@{{ include "pgvector.fullname" . }}-haproxy.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.postgresql.haproxy.service.port }}/{{ .Values.postgresql.postgresDatabase }}?sslmode=disable
{{- end }}
{{- end }}

