{{- if and .Values.postgresql.enabled (gt (int .Values.postgresql.replica.replicaCount) 0) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pgvector.fullname" . }}-postgresql-replica
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql-replica
spec:
  replicas: {{ .Values.postgresql.replica.replicaCount | int }}
  serviceName: {{ include "pgvector.fullname" . }}-postgresql-replica
  selector:
    matchLabels:
      {{- include "pgvector.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql-replica
  template:
    metadata:
      labels:
        {{- include "pgvector.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql-replica
      {{- with .Values.postgresql.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "pgvector.serviceAccountName" . }}
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      initContainers:
        - name: init-replica
          image: {{ .Values.postgresql.image.registry }}/{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
          command:
            - /bin/sh
            - -c
            - |
              set -e

              mkdir -p /var/lib/postgresql/data

              if [ ! -f /var/lib/postgresql/data/standby.signal ]; then
                until pg_isready -h {{ include "pgvector.fullname" . }}-postgresql-master.{{ .Release.Namespace }}.svc.cluster.local -p 5432 -U {{ .Values.postgresql.postgresUser }}; do
                  sleep 2
                done

                rm -rf /var/lib/postgresql/data/*

                PGPASSWORD={{ .Values.postgresql.postgresPassword | default (include "pgvector.postgresql.password" .) }} pg_basebackup \
                  -h {{ include "pgvector.fullname" . }}-postgresql-master.{{ .Release.Namespace }}.svc.cluster.local \
                  -D /var/lib/postgresql/data \
                  -U {{ .Values.postgresql.postgresUser }} \
                  -P \
                  -v \
                  -R \
                  -X stream

                cat <<'EOF' > /var/lib/postgresql/data/pg_hba.conf
                # TYPE  DATABASE        USER            ADDRESS                 METHOD

                local   all             all                                     trust
                host    all             all             127.0.0.1/32            trust
                host    all             all             ::1/128                 trust
                host    replication     {{ .Values.postgresql.postgresUser }}        0.0.0.0/0               md5
                host    all             {{ .Values.postgresql.postgresUser }}        0.0.0.0/0               md5
                EOF
              fi
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgresql-replica
          image: {{ .Values.postgresql.image.registry }}/{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresUser | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgvector.postgresql.secretName" . }}
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresDatabase | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data
          command:
            - docker-entrypoint.sh
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.postgresql.replica.resources | nindent 12 }}
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: postgresql-config
              mountPath: /etc/postgresql
      volumes:
        - name: postgresql-config
          configMap:
            name: {{ include "pgvector.fullname" . }}-postgresql-replica-config
        {{- if not .Values.postgresql.replica.persistence.enabled }}
        - name: postgresql-data
          emptyDir: {}
        {{- end }}
      {{- with .Values.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.postgresql.replica.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes:
        {{- range .Values.postgresql.replica.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.replica.persistence.size | default "1Gi" }}
        {{- if .Values.postgresql.replica.persistence.storageClass }}
        storageClassName: "{{ .Values.postgresql.replica.persistence.storageClass }}"
        {{- end }}
  {{- end }}
{{- end }}

