{{- if .Values.postgresql.enabled }}
{{- $user := .Values.postgresql.postgresUser -}}
{{- $password := .Values.postgresql.postgresPassword -}}
{{- $database := .Values.postgresql.postgresDatabase -}}
{{- if .Values.postgresql.existingSecret }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.existingSecret) -}}
  {{- $secret = required (printf "Secret '%s' not found in namespace '%s'" .Values.postgresql.existingSecret .Release.Namespace) $secret -}}
  {{- $secretData := index $secret "data" | default dict -}}
  {{- if not (hasKey $secretData "postgres-user") }}
    {{- fail (printf "Secret '%s' must contain key 'postgres-user'" .Values.postgresql.existingSecret) -}}
  {{- end }}
  {{- $user = (index $secretData "postgres-user" | b64dec) -}}
  {{- if hasKey $secretData "postgres-password" }}
    {{- $password = (index $secretData "postgres-password" | b64dec) -}}
  {{- end }}
  {{- if not (hasKey $secretData "postgres-database") }}
    {{- fail (printf "Secret '%s' must contain key 'postgres-database'" .Values.postgresql.existingSecret) -}}
  {{- end }}
  {{- $database = (index $secretData "postgres-database" | b64dec) -}}
{{- end }}
{{- $user = required "postgresql.postgresUser must be provided (either via values or existing secret key postgres-user)" $user -}}
{{- $password = default (include "pgvector.postgresql.password" .) $password -}}
{{- $database = required "postgresql.postgresDatabase must be provided (either via values or existing secret key postgres-database)" $database -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgvector.postgresql.urlSecretName" . }}
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql-secret
type: Opaque
stringData:
  postgres-password: {{ $password | quote }}
  postgres-user: {{ $user | quote }}
  postgres-database: {{ $database | quote }}
  postgres-host: {{ include "pgvector.fullname" . }}-postgresql-master.{{ .Release.Namespace }}.svc.cluster.local
  postgres-port: "5432"
  postgres-url: {{ include "pgvector.postgresql.connectionString" . | quote }}
  replica-host: {{ include "pgvector.fullname" . }}-postgresql-replica.{{ .Release.Namespace }}.svc.cluster.local
  replica-port: "5432"
  replica-url: postgresql://{{ $user }}:{{ $password }}@{{ include "pgvector.fullname" . }}-postgresql-replica.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ $database }}?sslmode=disable
{{- if .Values.postgresql.pgbouncer.enabled }}
  pgbouncer-host: {{ include "pgvector.fullname" . }}-pgbouncer.{{ .Release.Namespace }}.svc.cluster.local
  pgbouncer-port: "{{ .Values.postgresql.pgbouncer.service.port }}"
  pgbouncer-url: postgresql://{{ $user }}:{{ $password }}@{{ include "pgvector.fullname" . }}-pgbouncer.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.postgresql.pgbouncer.service.port }}/{{ $database }}?sslmode=disable
{{- end }}
{{- if .Values.postgresql.haproxy.enabled }}
  haproxy-host: {{ include "pgvector.fullname" . }}-haproxy.{{ .Release.Namespace }}.svc.cluster.local
  haproxy-port: "{{ .Values.postgresql.haproxy.service.port }}"
  haproxy-url: postgresql://{{ $user }}:{{ $password }}@{{ include "pgvector.fullname" . }}-haproxy.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.postgresql.haproxy.service.port }}/{{ $database }}?sslmode=disable
{{- end }}
{{- end }}
