{{- if and .Values.postgresql.enabled .Values.postgresql.repmgr.enabled (not .Values.postgresql.repmgr.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgvector.postgresql.repmgr.secretName" . }}
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: repmgr-secret
type: Opaque
data:
  repmgr-password: {{ .Values.postgresql.repmgr.password | default (include "pgvector.postgresql.repmgr.password" .) | b64enc | quote }}
{{- end }}
