{{- if .Values.postgresql.enabled }}
{{- $secretName := include "pgvector.postgresql.secretName" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pgvector.fullname" . }}-postgresql-master
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql-master
spec:
  replicas: {{ .Values.postgresql.master.replicaCount | int }}
  serviceName: {{ include "pgvector.fullname" . }}-postgresql-master
  selector:
    matchLabels:
      {{- include "pgvector.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql-master
  template:
    metadata:
      labels:
        {{- include "pgvector.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql-master
      {{- with .Values.postgresql.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "pgvector.serviceAccountName" . }}
      {{- $imagePullSecrets := .Values.postgresql.imagePullSecrets | default list }}
      {{- if and .Values.postgresql.repmgr.enabled .Values.postgresql.repmgr.imagePullSecrets }}
      {{- $imagePullSecrets = concat $imagePullSecrets .Values.postgresql.repmgr.imagePullSecrets }}
      {{- end }}
      {{- if $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-postgresql
          image: {{ .Values.postgresql.image.registry }}/{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: postgres-database
            - name: REPLICATION_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgvector.fullname" . }}-postgresql-replication-secret
                  key: replication-user
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /var/lib/postgresql/data

              if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
                export PGDATA=/var/lib/postgresql/data
                rm -rf /var/lib/postgresql/data/*
                /usr/local/bin/docker-entrypoint.sh postgres --initialize-only
              fi

              cat <<EOF > /tmp/pg_hba.conf
              # TYPE  DATABASE        USER            ADDRESS                 METHOD

              local   all             all                                     trust
              host    all             all             127.0.0.1/32            trust
              host    all             all             ::1/128                 trust

              host    replication     ${REPLICATION_USER}        10.0.0.0/8              md5
              host    replication     ${REPLICATION_USER}        172.16.0.0/12           md5
              host    replication     ${REPLICATION_USER}        192.168.0.0/16          md5

              host    all             ${POSTGRES_USER}        10.0.0.0/8              md5
              host    all             ${POSTGRES_USER}        172.16.0.0/12           md5
              host    all             ${POSTGRES_USER}        192.168.0.0/16          md5

              host    all             all             0.0.0.0/0               md5
              EOF

              cp /tmp/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
              chown postgres:postgres /var/lib/postgresql/data/pg_hba.conf
              chmod 600 /var/lib/postgresql/data/pg_hba.conf
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgresql-master
          image: {{ .Values.postgresql.image.registry }}/{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: postgres-database
            - name: REPLICATION_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgvector.fullname" . }}-postgresql-replication-secret
                  key: replication-user
            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgvector.fullname" . }}-postgresql-replication-secret
                  key: replication-password
            - name: PGDATA
              value: /var/lib/postgresql/data
          command:
            - docker-entrypoint.sh
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    set -e
                    export PGPASSWORD="${POSTGRES_PASSWORD}"
                    until pg_isready -U "${POSTGRES_USER}" -d postgres; do
                      sleep 1
                    done
                    psql -U "${POSTGRES_USER}" -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = '${POSTGRES_DB}'" | grep -q 1 || psql -U "${POSTGRES_USER}" -d postgres -c "CREATE DATABASE ${POSTGRES_DB};"
                    psql -U "${POSTGRES_USER}" -d postgres -tc "SELECT 1 FROM pg_roles WHERE rolname = '${REPLICATION_USER}'" | grep -q 1 || psql -U "${POSTGRES_USER}" -d postgres -c "CREATE USER ${REPLICATION_USER} WITH REPLICATION PASSWORD '${REPLICATION_PASSWORD}';"
                    psql -U "${POSTGRES_USER}" -d postgres -c "ALTER USER ${REPLICATION_USER} WITH PASSWORD '${REPLICATION_PASSWORD}';"
                    psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -tc "SELECT 1 FROM pg_available_extensions WHERE name = 'vector'" | grep -q 1 && psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -c "CREATE EXTENSION IF NOT EXISTS vector;" || true
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.postgresql.master.resources | nindent 12 }}
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: postgresql-config
              mountPath: /etc/postgresql
        {{- if .Values.postgresql.repmgr.enabled }}
        - name: repmgr
          image: {{ .Values.postgresql.repmgr.image.registry }}/{{ .Values.postgresql.repmgr.image.repository }}:{{ .Values.postgresql.repmgr.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.repmgr.image.pullPolicy }}
          command: ["/usr/local/bin/entrypoint.sh", "init"]
          env:
            - name: NODE_TYPE
              value: "master"
            - name: NODE_ID
              value: {{ .Values.postgresql.repmgr.nodeId | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: {{ .Values.postgresql.repmgr.clusterName | quote }}
            - name: REPMGR_DB
              value: {{ .Values.postgresql.repmgr.db | quote }}
            - name: REPMGR_USER
              value: {{ .Values.postgresql.repmgr.user | quote }}
            - name: REPMGR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgvector.postgresql.repmgr.secretName" . }}
                  key: repmgr-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: postgres-password
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: repmgr-config
              mountPath: /etc/repmgr
          resources:
            {{- toYaml .Values.postgresql.repmgr.resources | nindent 12 }}
        - name: repmgrd
          image: {{ .Values.postgresql.repmgr.image.registry }}/{{ .Values.postgresql.repmgr.image.repository }}:{{ .Values.postgresql.repmgr.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.repmgr.image.pullPolicy }}
          command: ["/usr/local/bin/entrypoint.sh", "repmgrd"]
          env:
            - name: REPMGR_DB
              value: {{ .Values.postgresql.repmgr.db | quote }}
            - name: REPMGR_USER
              value: {{ .Values.postgresql.repmgr.user | quote }}
            - name: REPMGR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgvector.postgresql.repmgr.secretName" . }}
                  key: repmgr-password
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: repmgr-config
              mountPath: /etc/repmgr
            - name: repmgr-logs
              mountPath: /var/log/repmgr
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        {{- if .Values.postgresql.repmgr.serviceUpdater.enabled }}
        - name: service-updater
          image: {{ .Values.postgresql.repmgr.image.registry }}/{{ .Values.postgresql.repmgr.image.repository }}:{{ .Values.postgresql.repmgr.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.repmgr.image.pullPolicy }}
          command: ["/usr/local/bin/entrypoint.sh", "service-updater"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MASTER_SERVICE
              value: {{ printf "%s-postgresql-master" (include "pgvector.fullname" .) | quote }}
            - name: REPMGR_DB
              value: {{ .Values.postgresql.repmgr.db | quote }}
            - name: REPMGR_USER
              value: {{ .Values.postgresql.repmgr.user | quote }}
            - name: REPMGR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgvector.postgresql.repmgr.secretName" . }}
                  key: repmgr-password
            - name: MONITORING_INTERVAL
              value: {{ .Values.postgresql.repmgr.serviceUpdater.monitoringInterval | quote }}
          volumeMounts:
            - name: repmgr-config
              mountPath: /etc/repmgr
          resources:
            {{- toYaml .Values.postgresql.repmgr.serviceUpdater.resources | nindent 12 }}
        {{- end }}
        {{- end }}
      volumes:
        - name: postgresql-config
          configMap:
            name: {{ include "pgvector.fullname" . }}-postgresql-master-config
        {{- if .Values.postgresql.repmgr.enabled }}
        - name: repmgr-config
          emptyDir: {}
        - name: repmgr-logs
          emptyDir: {}
        {{- end }}
        {{- if not .Values.postgresql.master.persistence.enabled }}
        - name: postgresql-data
          emptyDir: {}
        {{- end }}
      {{- with .Values.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.postgresql.master.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes:
        {{- range .Values.postgresql.master.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.master.persistence.size | default "1Gi" }}
        {{- if .Values.postgresql.master.persistence.storageClass }}
        storageClassName: "{{ .Values.postgresql.master.persistence.storageClass }}"
        {{- end }}
  {{- end }}
{{- end }}

