{{- if .Values.postgresql.enabled }}
{{- $replicationUser := include "pgvector.postgresql.replicationUser" . -}}
{{- $replicationPassword := include "pgvector.postgresql.replicationPassword" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgvector.fullname" . }}-postgresql-replication-secret
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql-replication-secret
type: Opaque
stringData:
  replication-user: {{ $replicationUser | quote }}
  replication-password: {{ $replicationPassword | quote }}
{{- end }}

