{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pgvector.serviceAccountName" . }}
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
  {{- $annotations := include "pgvector.annotations" (dict "global" $.Values.annotations "component" .Values.serviceAccount.annotations) | fromYaml -}}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

