apiVersion: v2
name: pg
description: PostgreSQL with repmgr replication and optional PGPool-II
type: application
version: 0.5.82
appVersion: "18.1"
home: https://github.com/cagriekin/charts/tree/master/pg
icon: https://wiki.postgresql.org/images/a/a4/PostgreSQL_logo.3colors.svg
sources:
  - https://github.com/cagriekin/charts
  - https://www.postgresql.org
  - https://repmgr.org
  - https://www.pgpool.net
keywords:
  - PostgreSQL
  - Database
  - SQL
  - Replication
  - repmgr
  - PGPool-II
  - High Availability
maintainers:
  - name: cagriekin
    email: cagri.ekin@gmail.com
    url: https://github.com/cagriekin
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
