{{- if and .Values.kafka.enabled (include "kafka.tls.selfSigned" .) }}
{{- $fullname := include "kafka.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $fullname }}-kafka-selfsigned
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-tls
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullname }}-kafka-ca
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-tls
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
spec:
  isCA: true
  commonName: {{ $fullname }}-kafka-ca
  secretName: {{ $fullname }}-kafka-ca
  duration: 87600h
  renewBefore: 2160h
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
    - cert sign
    - crl sign
  issuerRef:
    name: {{ $fullname }}-kafka-selfsigned
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $fullname }}-kafka-ca
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-tls
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
spec:
  ca:
    secretName: {{ $fullname }}-kafka-ca
{{- end }}
