{{- if .Values.kafka.enabled }}
{{- $chartUsers := list }}
{{- range .Values.kafka.auth.users }}
{{- if not .existingSecret }}
{{- $chartUsers = append $chartUsers . }}
{{- end }}
{{- end }}
{{- if $chartUsers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka.auth.secretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-secret
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
type: Opaque
stringData:
  {{- range $u := $chartUsers }}
  {{ $u.username }}-password: {{ include "kafka.auth.userPassword" (dict "ctx" $ "user" $u) | quote }}
  {{- end }}
{{- end }}
{{- end }}
