{{- if and .Values.kafka.enabled (not .Values.kafka.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka.fullname" . }}-kafka-secret
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-secret
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
type: Opaque
stringData:
  {{- $username := .Values.kafka.auth.username | default "user1" }}
  {{- $rawPassword := .Values.kafka.auth.password | default (include "kafka.kafka.password" .) }}
  {{- $password := $rawPassword | b64dec }}
  password: {{ $password | quote }}
  username: {{ $username | quote }}
{{- end }}
