{{- if .Values.kafka.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kafka.fullname" . }}-kafka-topic-init-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-topic-init
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kafka-topic-init
        image: {{ .Values.kafka.image.registry }}/{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}
        volumeMounts:
        - name: kafka-config
          mountPath: /opt/kafka/config/kraft
        {{- $root := . }}
        command:
        - /bin/bash
        - -c
        - |
          set -e
          BOOTSTRAP_SERVER="{{ include "kafka.fullname" . }}-kafka-broker.{{ default "default" .Release.Namespace }}.svc.cluster.local:9092"
          MAX_ATTEMPTS=${KAFKA_BOOTSTRAP_RETRIES:-30}
          SLEEP_SECONDS=${KAFKA_BOOTSTRAP_SLEEP:-5}

          echo "Waiting for Kafka bootstrap server ${BOOTSTRAP_SERVER} to become reachable..."
          ATTEMPT=1
          until /opt/kafka/bin/kafka-broker-api-versions.sh \
            --bootstrap-server "${BOOTSTRAP_SERVER}" \
            --command-config /opt/kafka/config/kraft/client.properties >/dev/null 2>&1; do
            if [ "${ATTEMPT}" -ge "${MAX_ATTEMPTS}" ]; then
              echo "Kafka bootstrap server still unreachable after ${ATTEMPT} attempts; giving up." >&2
              exit 1
            fi

            echo "Attempt ${ATTEMPT}/${MAX_ATTEMPTS} failed. Broker not ready yet; sleeping ${SLEEP_SECONDS}s..."
            ATTEMPT=$((ATTEMPT + 1))
            sleep "${SLEEP_SECONDS}"
          done

          echo "Kafka bootstrap server reachable."

          # Kafka broker should be ready. Creating topics...
          echo "Creating topics..."
          export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/kafka/config/kraft/client_jaas.conf"

          # Ensure configured topics exist
{{- range $topicName, $topic := $root.Values.kafka.topics }}
          echo "Ensuring {{ $topicName }} topic exists..."
          /opt/kafka/bin/kafka-topics.sh \
            --create \
            --bootstrap-server ${BOOTSTRAP_SERVER} \
            --command-config /opt/kafka/config/kraft/client.properties \
            --topic {{ $topicName }} \
            --partitions {{ default 1 $topic.partitions }} \
            --replication-factor {{ default 1 $topic.replicationFactor }} \
            {{- with $topic.config }}
            {{- range $confKey, $confValue := . }}
            --config {{ $confKey }}={{ $confValue }} \
            {{- end }}
            {{- end }}
            --if-not-exists

{{- end }}

          echo "Topics created successfully. Listing all topics:"
          /opt/kafka/bin/kafka-topics.sh \
            --list \
            --bootstrap-server ${BOOTSTRAP_SERVER} \
            --command-config /opt/kafka/config/kraft/client.properties
      volumes:
      - name: kafka-config
        configMap:
          name: {{ include "kafka.fullname" . }}-kafka-broker-config
{{- end }}

