{{- if .Values.kafka.enabled }}
{{- $brokerProtocol := include "kafka.broker.listenerProtocol" . -}}
{{- $controllerSecProtocol := include "kafka.controller.listenerSecurityProtocol" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}-kafka-controller-config
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-controller-config
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
data:
  kafka_server_jaas.conf.template: |
    KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="PLACEHOLDER_USERNAME"
        password="PLACEHOLDER_PASSWORD"
        user_PLACEHOLDER_USERNAME="PLACEHOLDER_PASSWORD";
    };
  server.properties: |
    process.roles=controller
    node.id=PLACEHOLDER_NODE_ID
    controller.quorum.voters={{ include "kafka.kafka.controllerQuorumVoters" . }}
    listeners=CONTROLLER://:9093
    listener.security.protocol.map=CONTROLLER:{{ $controllerSecProtocol }}
    controller.listener.names=CONTROLLER
    log.dirs={{ .Values.kafka.controller.logDir }}
    {{- if .Values.kafka.tls.enabled }}
    ssl.keystore.type=PKCS12
    ssl.keystore.location=/opt/kafka/tls/keystore.p12
    ssl.keystore.password={{ include "kafka.tls.storePassword" . }}
    ssl.truststore.type=PKCS12
    ssl.truststore.location=/opt/kafka/tls/truststore.p12
    ssl.truststore.password={{ include "kafka.tls.storePassword" . }}
    ssl.endpoint.identification.algorithm=
    {{- end }}
  client.properties: |
    security.protocol={{ $brokerProtocol }}
    sasl.mechanism=PLAIN
    {{- if .Values.kafka.tls.enabled }}
    ssl.truststore.type=PKCS12
    ssl.truststore.location=/opt/kafka/tls/truststore.p12
    ssl.truststore.password={{ include "kafka.tls.storePassword" . }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}-kafka-broker-config
  labels:
    app.kubernetes.io/name: {{ include "kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-broker-config
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    helm.sh/chart: {{ include "kafka.chart" . }}
data:
  kafka_server_jaas.conf.template: |
    KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="PLACEHOLDER_USERNAME"
        password="PLACEHOLDER_PASSWORD"
        user_PLACEHOLDER_USERNAME="PLACEHOLDER_PASSWORD";
    };
  server.properties: |
    process.roles=broker
    node.id=PLACEHOLDER_NODE_ID
    controller.quorum.voters={{ include "kafka.kafka.controllerQuorumVoters" . }}
    listeners={{ $brokerProtocol }}://:9092
    listener.security.protocol.map={{ $brokerProtocol }}:{{ $brokerProtocol }},CONTROLLER:{{ $controllerSecProtocol }}
    controller.listener.names=CONTROLLER
    advertised.listeners={{ $brokerProtocol }}://PLACEHOLDER_POD_NAME.{{ include "kafka.fullname" . }}-kafka-broker.{{ default "default" .Release.Namespace }}.svc.cluster.local:9092
    inter.broker.listener.name={{ $brokerProtocol }}
    num.partitions={{ .Values.kafka.broker.config.numPartitions }}
    default.replication.factor={{ .Values.kafka.broker.config.defaultReplicationFactor }}
    min.insync.replicas={{ .Values.kafka.broker.config.minInsyncReplicas }}
    offsets.topic.replication.factor={{ .Values.kafka.broker.config.offsetsTopicReplicationFactor }}
    transaction.state.log.min.isr={{ .Values.kafka.broker.config.transactionStateLogMinIsr }}
    transaction.state.log.replication.factor={{ .Values.kafka.broker.config.transactionStateLogReplicationFactor }}
    num.io.threads={{ .Values.kafka.broker.config.numIoThreads }}
    num.network.threads={{ .Values.kafka.broker.config.numNetworkThreads }}
    num.replica.fetchers={{ .Values.kafka.broker.config.numReplicaFetchers }}
    log.retention.hours={{ .Values.kafka.broker.config.logRetentionHours }}
    log.retention.bytes={{ .Values.kafka.broker.config.logRetentionBytes | int64 }}
    log.segment.bytes={{ .Values.kafka.broker.config.logSegmentBytes | int64 }}
    log.cleanup.policy={{ .Values.kafka.broker.config.logCleanupPolicy }}
    auto.create.topics.enable={{ .Values.kafka.autoCreateTopicsEnable }}
    delete.topic.enable={{ .Values.kafka.deleteTopicEnable }}
    log.dirs={{ .Values.kafka.broker.logDir }}
    sasl.enabled.mechanisms=PLAIN
    sasl.mechanism.inter.broker.protocol=PLAIN
    sasl.jaas.config=/opt/kafka/config/kraft/kafka_server_jaas.conf
    {{- if .Values.kafka.tls.enabled }}
    ssl.keystore.type=PKCS12
    ssl.keystore.location=/opt/kafka/tls/keystore.p12
    ssl.keystore.password={{ include "kafka.tls.storePassword" . }}
    ssl.truststore.type=PKCS12
    ssl.truststore.location=/opt/kafka/tls/truststore.p12
    ssl.truststore.password={{ include "kafka.tls.storePassword" . }}
    ssl.endpoint.identification.algorithm=
    {{- end }}
    {{- range $key, $value := .Values.kafka.broker.extraConfig }}
    {{ $key }}={{ $value }}
    {{- end }}
  server-init.properties: |
    process.roles=broker
    node.id=PLACEHOLDER_NODE_ID
    controller.quorum.voters={{ include "kafka.kafka.controllerQuorumVoters" . }}
    listeners={{ $brokerProtocol }}://:9092
    listener.security.protocol.map={{ $brokerProtocol }}:{{ $brokerProtocol }},CONTROLLER:{{ $controllerSecProtocol }}
    controller.listener.names=CONTROLLER
    inter.broker.listener.name={{ $brokerProtocol }}
    num.partitions={{ .Values.kafka.broker.config.numPartitions }}
    default.replication.factor={{ .Values.kafka.broker.config.defaultReplicationFactor }}
    offsets.topic.replication.factor={{ .Values.kafka.broker.config.offsetsTopicReplicationFactor }}
    transaction.state.log.min.isr={{ .Values.kafka.broker.config.transactionStateLogMinIsr }}
    transaction.state.log.replication.factor={{ .Values.kafka.broker.config.transactionStateLogReplicationFactor }}
    auto.create.topics.enable={{ .Values.kafka.autoCreateTopicsEnable }}
    delete.topic.enable={{ .Values.kafka.deleteTopicEnable }}
    log.dirs={{ .Values.kafka.broker.logDir }}
    sasl.enabled.mechanisms=PLAIN
    sasl.mechanism.inter.broker.protocol=PLAIN
    sasl.jaas.config=/opt/kafka/config/kraft/kafka_server_jaas.conf
  client.properties: |
    security.protocol={{ $brokerProtocol }}
    sasl.mechanism=PLAIN
    {{- if .Values.kafka.tls.enabled }}
    ssl.truststore.type=PKCS12
    ssl.truststore.location=/tmp/kafka-config/truststore.p12
    ssl.truststore.password={{ include "kafka.tls.storePassword" . }}
    {{- end }}
  client_jaas.conf.template: |
    KafkaClient {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="PLACEHOLDER_USERNAME"
        password="PLACEHOLDER_PASSWORD";
    };
{{- end }}
