{{- if .Values.exporters.kafka.enabled }}
{{- include "common.exporterDeployment" (dict
  "ctx"             .
  "component"       "kafka-exporter"
  "labels"          "kafka.labels"
  "selectorLabels"  "kafka.selectorLabels"
  "replicas"        .Values.exporters.kafka.replicaCount
  "podAnnotations"  .Values.exporters.kafka.podAnnotations
  "podSpec"         "kafka.exporterPodSpec"
) }}
{{- end }}
