apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with (include "redis.globalAnnotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  redis.conf: |
    appendonly yes
    appendfsync {{ .Values.redis.config.appendfsync }}
    no-appendfsync-on-rewrite {{ index .Values.redis.config "no-appendfsync-on-rewrite" }}
    auto-aof-rewrite-percentage {{ index .Values.redis.config "auto-aof-rewrite-percentage" }}
    auto-aof-rewrite-min-size {{ index .Values.redis.config "auto-aof-rewrite-min-size" }}
    maxmemory {{ .Values.redis.config.maxmemory }}
    maxmemory-policy {{ index .Values.redis.config "maxmemory-policy" }}
    tcp-keepalive 60
    timeout 0
{{- if .Values.redis.config.rdbSnapshots }}
{{- range .Values.redis.config.rdbSnapshots }}
    save {{ .seconds }} {{ .changes }}
{{- end }}
{{- else }}
    save ""
{{- end }}
{{- if eq .Values.architecture "replication" }}
    replica-read-only {{ index .Values.redis.config "replica-read-only" }}
    min-replicas-to-write {{ index .Values.redis.config "min-replicas-to-write" }}
    min-replicas-max-lag {{ index .Values.redis.config "min-replicas-max-lag" }}
{{- end }}
{{- if .Values.tls.enabled }}
    port 0
    tls-port {{ .Values.service.port }}
    tls-cert-file /etc/redis/tls/tls.crt
    tls-key-file /etc/redis/tls/tls.key
    tls-ca-cert-file /etc/redis/tls/ca.crt
    tls-auth-clients {{ if .Values.tls.clientCertAuth }}yes{{ else }}no{{ end }}
{{- if eq .Values.architecture "replication" }}
    tls-replication yes
{{- end }}
{{- end }}
{{- if eq .Values.architecture "replication" }}
  sentinel.conf: |
{{- if .Values.tls.enabled }}
    port 0
    tls-port {{ .Values.sentinel.service.port }}
    tls-cert-file /etc/redis/tls/tls.crt
    tls-key-file /etc/redis/tls/tls.key
    tls-ca-cert-file /etc/redis/tls/ca.crt
    tls-auth-clients {{ if .Values.tls.clientCertAuth }}yes{{ else }}no{{ end }}
    tls-replication yes
{{- else }}
    port {{ .Values.sentinel.service.port }}
{{- end }}
    dir /config-rw
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
  bootstrap.sh: |
    {{- include "redis.bootstrapScript" . | nindent 4 }}
{{- end }}
