{{- if .Values.exporter.enabled }}
{{- include "common.exporterDeployment" (dict
  "ctx"             .
  "component"       "redis-exporter"
  "nameSuffix"      "exporter"
  "labels"          "redis.labels"
  "selectorLabels"  "redis.selectorLabels"
  "podSpec"         "redis.exporterPodSpec"
) }}
{{- end }}
