{{- if .Values.networkPolicy.enabled }}
{{- $repl := eq .Values.architecture "replication" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  podSelector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
{{- if $repl }}
        - port: {{ .Values.sentinel.service.port }}
          protocol: TCP
{{- if .Values.exporter.enabled }}
        - port: 9121
          protocol: TCP
{{- end }}
{{- end }}
      from:
{{- if and .Values.exporter.enabled (not $repl) }}
        - podSelector:
            matchLabels:
              {{- include "redis.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: redis-exporter
{{- end }}
{{- if $repl }}
        - podSelector:
            matchLabels:
              {{- include "redis.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: redis
{{- end }}
{{- if .Values.networkPolicy.allowExternal }}
        - podSelector: {}
{{- end }}
{{- with .Values.networkPolicy.extraIngress }}
        {{- toYaml . | nindent 8 }}
{{- end }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- if $repl }}
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
        - port: {{ .Values.sentinel.service.port }}
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              {{- include "redis.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: redis
{{- end }}
{{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- if and .Values.exporter.enabled (not $repl) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "redis.fullname" . }}-exporter
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-exporter
spec:
  podSelector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis-exporter
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 9121
          protocol: TCP
      from:
        - podSelector: {}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              {{- include "redis.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: redis
{{- end }}
{{- end }}
