{{- if and .Values.exporter.enabled .Values.exporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "redis.fullname" . }}-exporter
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-exporter
    {{- with .Values.exporter.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis-exporter
  endpoints:
    - port: metrics
      interval: {{ .Values.exporter.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.exporter.serviceMonitor.scrapeTimeout }}
      path: /metrics
{{- end }}
