{{- if and .Values.pgpool.enabled (not .Values.pgpool.admin.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg.fullname" . }}-pgpool-admin
  labels:
    {{- include "pg.labels" . | nindent 4 }}
  {{- with (include "pg.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ required "pgpool.admin.username is required when pgpool.admin.existingSecret is disabled" .Values.pgpool.admin.username | b64enc | quote }}
  password: {{ required "pgpool.admin.password is required when pgpool.admin.existingSecret is disabled" .Values.pgpool.admin.password | b64enc | quote }}
{{- end }}
