{{- if and .Values.prometheusExporter.enabled .Values.prometheusExporter.serviceMonitor.enabled }}
{{- $endpoints := list }}
{{- range $i := until (add (int $.Values.postgresql.replicaCount) 1 | int) }}
{{- $ep := dict
  "port" "metrics"
  "interval" $.Values.prometheusExporter.serviceMonitor.interval
  "scrapeTimeout" $.Values.prometheusExporter.serviceMonitor.scrapeTimeout
  "path" "/probe"
  "params" (dict
    "auth_module" (list "postgres")
    "target" (list (printf "%s-%d.%s-headless.%s.svc.cluster.local:5432" (include "pg.fullname" $) $i (include "pg.fullname" $) $.Release.Namespace))
  )
  "relabelings" (list
    (dict "sourceLabels" (list "__param_target") "targetLabel" "instance")
    (dict "sourceLabels" (list) "targetLabel" "job" "replacement" (printf "%s-postgresql" (include "pg.fullname" $)))
  )
}}
{{- $endpoints = append $endpoints $ep }}
{{- end }}
{{- include "common.exporterServiceMonitor" (dict
  "ctx"             .
  "component"       "postgres-exporter"
  "labels"          "pg.labels"
  "selectorLabels"  "pg.selectorLabels"
  "additionalLabels" .Values.prometheusExporter.serviceMonitor.additionalLabels
  "endpoints"       $endpoints
) }}
{{- end }}
