{{- if .Values.prometheusExporter.enabled }}
{{- $annotations := dict
  "checksum/config" (include (print $.Template.BasePath "/prometheus-exporter-configmap.yaml") . | sha256sum)
  "prometheus.io/scrape" "true"
  "prometheus.io/port" "9116"
  "prometheus.io/path" "/metrics"
}}
{{- range $k, $v := .Values.prometheusExporter.podAnnotations }}
{{- $_ := set $annotations $k $v }}
{{- end }}
{{- include "common.exporterDeployment" (dict
  "ctx"             .
  "component"       "postgres-exporter"
  "labels"          "pg.labels"
  "selectorLabels"  "pg.selectorLabels"
  "podAnnotations"  $annotations
  "podSpec"         "pg.exporterPodSpec"
) }}
{{- end }}
