{{- if .Values.prometheusExporter.enabled }}
{{- include "common.exporterService" (dict
  "ctx"             .
  "component"       "postgres-exporter"
  "labels"          "pg.labels"
  "selectorLabels"  "pg.selectorLabels"
  "port"            .Values.prometheusExporter.service.port
  "serviceType"     .Values.prometheusExporter.service.type
  "annotations"     (merge (deepCopy .Values.prometheusExporter.service.annotations) .Values.global.annotations)
) }}
{{- end }}
