{{- if .Values.proxysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pg.fullname" . }}-proxysql
  labels:
    {{- include "pg.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxysql
spec:
  serviceName: {{ include "pg.fullname" . }}-proxysql-headless
  replicas: {{ .Values.proxysql.replicaCount }}
  selector:
    matchLabels:
      {{- include "pg.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxysql
  template:
    metadata:
      labels:
        {{- include "pg.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: proxysql
    spec:
      initContainers:
        - name: init-config
          image: busybox:1.35
          command:
            - /bin/sh
            - -c
            - |
              cp /config/proxysql.cnf /etc/proxysql/proxysql.cnf
              sed -i "s/__POSTGRES_USER__/$POSTGRES_USER/g" /etc/proxysql/proxysql.cnf
              sed -i "s/__POSTGRES_PASSWORD__/$POSTGRES_PASSWORD/g" /etc/proxysql/proxysql.cnf
              sed -i "s/__POSTGRES_DB__/$POSTGRES_DB/g" /etc/proxysql/proxysql.cnf
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "pg.secretName" . }}
                  key: {{ include "pg.secretUsernameKey" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pg.secretName" . }}
                  key: {{ include "pg.secretPasswordKey" . }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "pg.secretName" . }}
                  key: {{ include "pg.secretDatabaseKey" . }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: proxysql-config
              mountPath: /etc/proxysql
      containers:
        - name: proxysql
          image: "{{ .Values.proxysql.image.repository }}:{{ .Values.proxysql.image.tag }}"
          imagePullPolicy: {{ .Values.proxysql.image.pullPolicy }}
          ports:
            - name: proxysql
              containerPort: 6033
              protocol: TCP
            - name: admin
              containerPort: 6032
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6033
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 6033
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            {{- toYaml .Values.proxysql.resources | nindent 12 }}
          volumeMounts:
            - name: proxysql-config
              mountPath: /etc/proxysql
            - name: data
              mountPath: /var/lib/proxysql
      volumes:
        - name: config
          configMap:
            name: {{ include "pg.fullname" . }}-proxysql
        - name: proxysql-config
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
{{- end }}
