{{- if .Values.repmgr.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pg.fullname" . }}-repmgr
  labels:
    {{- include "pg.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pg.fullname" . }}-repmgr
  labels:
    {{- include "pg.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pg.fullname" . }}-repmgr
  labels:
    {{- include "pg.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pg.fullname" . }}-repmgr
subjects:
  - kind: ServiceAccount
    name: {{ include "pg.fullname" . }}-repmgr
    namespace: {{ .Release.Namespace }}
{{- end }}
