apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg.fullname" . }}-headless
  labels:
    {{- include "pg.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "pg.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
