apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pg.fullname" . }}
  labels:
    {{- include "pg.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "pg.fullname" . }}-headless
  replicas: {{ add .Values.postgresql.replicaCount 1 }}
  selector:
    matchLabels:
      {{- include "pg.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "pg.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "pg.secretName" . }}
                  key: {{ include "pg.secretUsernameKey" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pg.secretName" . }}
                  key: {{ include "pg.secretPasswordKey" . }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "pg.secretName" . }}
                  key: {{ include "pg.secretDatabaseKey" . }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    for i in {1..30}; do
                      if pg_isready -U postgres > /dev/null 2>&1; then
                        HBA_FILE=$(psql -U postgres -t -c "SHOW hba_file" | xargs)
                        if ! grep -q "host all all 10.0.0.0/8 trust" "$HBA_FILE"; then
                          sed -i '/host all all all scram-sha-256/i host all all 10.0.0.0/8 trust' "$HBA_FILE"
                          psql -U postgres -c "SELECT pg_reload_conf();" > /dev/null 2>&1
                        fi
                        {{- if .Values.postgresql.lifecycle.postStart.additionalCommands }}
                        {{ .Values.postgresql.lifecycle.postStart.additionalCommands | nindent 24 }}
                        {{- end }}
                        break
                      fi
                      sleep 1
                    done
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
{{- if not .Values.postgresql.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
{{- end }}
{{- if .Values.postgresql.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
{{- if .Values.postgresql.persistence.storageClass }}
        storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
{{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
