package pgconf

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// #308: PG17+'s sync_replication_slots worker requires dbname in primary_conninfo;
// repmgr's own clone/follow CLI never writes it (confirmed live against a real cluster).
// The exact line shape below is what was observed on a running standby's
// postgresql.auto.conf.
const liveConninfoLine = `primary_conninfo = 'host=''pg-0.headless'' port=5432 user=repmgr application_name=''pg-1'' connect_timeout=10'`

func TestAddDBNameToPrimaryConninfoAppendsWhenAbsent(t *testing.T) {
	conf := "# Do not edit this file manually!\n" + liveConninfoLine + "\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if !changed {
		t.Fatal("expected a change")
	}
	if !strings.Contains(out, "dbname=''repmgr''") {
		t.Errorf("dbname not appended:\n%s", out)
	}
	// Everything else must survive untouched.
	if !strings.Contains(out, "# Do not edit this file manually!") {
		t.Errorf("unrelated line was dropped:\n%s", out)
	}
	if !strings.Contains(out, "host=''pg-0.headless''") || !strings.Contains(out, "application_name=''pg-1''") {
		t.Errorf("existing conninfo fields were corrupted:\n%s", out)
	}
	// Round-trip: the re-escaped line must be parseable the same way again, and idempotent.
	out2, changed2, _ := addDBNameToPrimaryConninfo(out, "repmgr")
	if changed2 {
		t.Errorf("second call must be a no-op, got a change:\n%s", out2)
	}
	if out2 != out {
		t.Errorf("second call must return identical content:\nfirst:  %q\nsecond: %q", out, out2)
	}
}

func TestAddDBNameToPrimaryConninfoNoOpWhenAlreadyPresent(t *testing.T) {
	conf := `primary_conninfo = 'host=''pg-0.h'' port=5432 user=repmgr dbname=''repmgr'' application_name=''pg-1'''` + "\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if changed {
		t.Errorf("must not touch a line that already has dbname:\n%s", out)
	}
	if out != conf {
		t.Errorf("content must be byte-identical when unchanged")
	}
}

func TestAddDBNameToPrimaryConninfoNoOpWhenLineAbsent(t *testing.T) {
	conf := "# a primary has no primary_conninfo at all\nwal_log_hints = on\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if changed {
		t.Errorf("must not fabricate a primary_conninfo line: %q", out)
	}
	if out != conf {
		t.Errorf("content must be byte-identical when there is nothing to patch")
	}
}

func TestAddDBNameToPrimaryConninfoPreservesOtherLines(t *testing.T) {
	// #308: once synchronized_standby_slots reconciliation lands, postgresql.auto.conf on
	// a PRIMARY can carry an ALTER SYSTEM-set line too. Simulate a file carrying both an
	// unrelated GUC before and after the conninfo line to prove only the target line moves.
	conf := "synchronized_standby_slots = 'repmgr_slot_1001'\n" + liveConninfoLine + "\nsome_other_guc = on\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if !changed {
		t.Fatal("expected a change")
	}
	lines := strings.Split(out, "\n")
	if lines[0] != "synchronized_standby_slots = 'repmgr_slot_1001'" {
		t.Errorf("line before primary_conninfo was altered: %q", lines[0])
	}
	if lines[2] != "some_other_guc = on" {
		t.Errorf("line after primary_conninfo was altered: %q", lines[2])
	}
}

// PostgreSQL honors the LAST occurrence of a duplicate GUC in postgresql.auto.conf, not
// the first -- patching the first of two primary_conninfo lines would report
// changed=true (triggering a reload) while the live value never actually picks up
// dbname, since the second line still wins.
func TestAddDBNameToPrimaryConninfoPatchesLastOccurrenceNotFirst(t *testing.T) {
	first := `primary_conninfo = 'host=''pg-0.h'' port=5432 user=repmgr application_name=''pg-1'''`
	second := `primary_conninfo = 'host=''pg-2.h'' port=5432 user=repmgr application_name=''pg-1'''`
	conf := first + "\n" + second + "\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if !changed {
		t.Fatal("expected a change")
	}
	lines := strings.Split(out, "\n")
	if lines[0] != first {
		t.Errorf("first (losing) occurrence must be left untouched: %q", lines[0])
	}
	if !strings.Contains(lines[1], "dbname=''repmgr''") || !strings.Contains(lines[1], "pg-2.h") {
		t.Errorf("last (winning) occurrence must be the one patched: %q", lines[1])
	}
}

// A value that itself contains the literal text "dbname=" (e.g. inside an options
// string) must not be mistaken for an existing dbname keyword -- a bare
// strings.Contains would false-positive and skip patching.
func TestAddDBNameToPrimaryConninfoIgnoresDBNameSubstringInAnotherValue(t *testing.T) {
	conf := `primary_conninfo = 'host=''pg-0.h'' port=5432 user=repmgr options=''-c foo.dbname=bar'' application_name=''pg-1'''` + "\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if !changed {
		t.Fatalf("expected a change (the dbname= substring is inside options=, not a real keyword):\n%s", out)
	}
	if !strings.Contains(out, "dbname=''repmgr''") {
		t.Errorf("dbname not appended:\n%s", out)
	}
}

// A malformed line (no matching quote pair) is a distinct, log-worthy case from
// "dbname already present" -- both are ok=false, but only one means this parser does
// not recognize a line shape repmgr actually wrote.
func TestAddDBNameToPrimaryConninfoReportsMalformedLine(t *testing.T) {
	conf := "primary_conninfo = no-quotes-here\n"
	out, changed, malformed := addDBNameToPrimaryConninfo(conf, "repmgr")
	if changed {
		t.Errorf("must not touch a malformed line:\n%s", out)
	}
	if !malformed {
		t.Error("expected malformed=true for a line with no matching quote pair")
	}
	if out != conf {
		t.Error("content must be byte-identical when left untouched")
	}
}

func TestAddDBNameToPrimaryConninfoAlreadyPresentIsNotMalformed(t *testing.T) {
	conf := `primary_conninfo = 'host=''pg-0.h'' port=5432 user=repmgr dbname=''repmgr'''` + "\n"
	_, changed, malformed := addDBNameToPrimaryConninfo(conf, "repmgr")
	if changed {
		t.Error("must not touch a line that already has dbname")
	}
	if malformed {
		t.Error("dbname already present is benign, not malformed")
	}
}

func TestEnsurePrimaryConninfoDBNameWarnsOnMalformedLine(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "postgresql.auto.conf")
	if err := os.WriteFile(path, []byte("primary_conninfo = no-quotes-here\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	changed, err := EnsurePrimaryConninfoDBName(path, "repmgr")
	if changed {
		t.Error("must not report a change for a malformed line")
	}
	if err == nil {
		t.Fatal("expected an error a caller can log for a malformed line")
	}
}

func TestEnsurePrimaryConninfoDBName(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "postgresql.auto.conf")
	if err := os.WriteFile(path, []byte(liveConninfoLine+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	changed, err := EnsurePrimaryConninfoDBName(path, "repmgr")
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("expected a change")
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "dbname=''repmgr''") {
		t.Errorf("file not updated:\n%s", b)
	}

	// Idempotent: a second call on the now-patched file is a no-op.
	changed, err = EnsurePrimaryConninfoDBName(path, "repmgr")
	if err != nil {
		t.Fatal(err)
	}
	if changed {
		t.Error("second call must be a no-op")
	}
}

func TestEnsurePrimaryConninfoDBNameMissingFile(t *testing.T) {
	_, err := EnsurePrimaryConninfoDBName(filepath.Join(t.TempDir(), "nope.conf"), "repmgr")
	if err == nil {
		t.Fatal("expected an error for a missing file")
	}
}
