package pgconf

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// #308: PG17+'s sync_replication_slots worker requires dbname in primary_conninfo;
// repmgr's own clone/follow CLI never writes it (confirmed live against a real cluster).
// The exact line shape below is what was observed on a running standby's
// postgresql.auto.conf.
const liveConninfoLine = `primary_conninfo = 'host=''pg-0.headless'' port=5432 user=repmgr application_name=''pg-1'' connect_timeout=10'`

func TestAddDBNameToPrimaryConninfoAppendsWhenAbsent(t *testing.T) {
	conf := "# Do not edit this file manually!\n" + liveConninfoLine + "\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if !changed {
		t.Fatal("expected a change")
	}
	if !strings.Contains(out, "dbname=''repmgr''") {
		t.Errorf("dbname not appended:\n%s", out)
	}
	// Everything else must survive untouched.
	if !strings.Contains(out, "# Do not edit this file manually!") {
		t.Errorf("unrelated line was dropped:\n%s", out)
	}
	if !strings.Contains(out, "host=''pg-0.headless''") || !strings.Contains(out, "application_name=''pg-1''") {
		t.Errorf("existing conninfo fields were corrupted:\n%s", out)
	}
	// Round-trip: the re-escaped line must be parseable the same way again, and idempotent.
	out2, changed2, _ := addDBNameToPrimaryConninfo(out, "repmgr")
	if changed2 {
		t.Errorf("second call must be a no-op, got a change:\n%s", out2)
	}
	if out2 != out {
		t.Errorf("second call must return identical content:\nfirst:  %q\nsecond: %q", out, out2)
	}
}

func TestAddDBNameToPrimaryConninfoNoOpWhenAlreadyPresent(t *testing.T) {
	conf := `primary_conninfo = 'host=''pg-0.h'' port=5432 user=repmgr dbname=''repmgr'' application_name=''pg-1'''` + "\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if changed {
		t.Errorf("must not touch a line that already has dbname:\n%s", out)
	}
	if out != conf {
		t.Errorf("content must be byte-identical when unchanged")
	}
}

func TestAddDBNameToPrimaryConninfoNoOpWhenLineAbsent(t *testing.T) {
	conf := "# a primary has no primary_conninfo at all\nwal_log_hints = on\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if changed {
		t.Errorf("must not fabricate a primary_conninfo line: %q", out)
	}
	if out != conf {
		t.Errorf("content must be byte-identical when there is nothing to patch")
	}
}

func TestAddDBNameToPrimaryConninfoPreservesOtherLines(t *testing.T) {
	// #308: once synchronized_standby_slots reconciliation lands, postgresql.auto.conf on
	// a PRIMARY can carry an ALTER SYSTEM-set line too. Simulate a file carrying both an
	// unrelated GUC before and after the conninfo line to prove only the target line moves.
	conf := "synchronized_standby_slots = 'repmgr_slot_1001'\n" + liveConninfoLine + "\nsome_other_guc = on\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if !changed {
		t.Fatal("expected a change")
	}
	lines := strings.Split(out, "\n")
	if lines[0] != "synchronized_standby_slots = 'repmgr_slot_1001'" {
		t.Errorf("line before primary_conninfo was altered: %q", lines[0])
	}
	if lines[2] != "some_other_guc = on" {
		t.Errorf("line after primary_conninfo was altered: %q", lines[2])
	}
}

// PostgreSQL honors the LAST occurrence of a duplicate GUC in postgresql.auto.conf, not
// the first -- patching the first of two primary_conninfo lines would report
// changed=true (triggering a reload) while the live value never actually picks up
// dbname, since the second line still wins.
func TestAddDBNameToPrimaryConninfoPatchesLastOccurrenceNotFirst(t *testing.T) {
	first := `primary_conninfo = 'host=''pg-0.h'' port=5432 user=repmgr application_name=''pg-1'''`
	second := `primary_conninfo = 'host=''pg-2.h'' port=5432 user=repmgr application_name=''pg-1'''`
	conf := first + "\n" + second + "\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if !changed {
		t.Fatal("expected a change")
	}
	lines := strings.Split(out, "\n")
	if lines[0] != first {
		t.Errorf("first (losing) occurrence must be left untouched: %q", lines[0])
	}
	if !strings.Contains(lines[1], "dbname=''repmgr''") || !strings.Contains(lines[1], "pg-2.h") {
		t.Errorf("last (winning) occurrence must be the one patched: %q", lines[1])
	}
}

// A value that itself contains the literal text "dbname=" (e.g. inside an options
// string) must not be mistaken for an existing dbname keyword -- a bare
// strings.Contains would false-positive and skip patching.
func TestAddDBNameToPrimaryConninfoIgnoresDBNameSubstringInAnotherValue(t *testing.T) {
	conf := `primary_conninfo = 'host=''pg-0.h'' port=5432 user=repmgr options=''-c foo.dbname=bar'' application_name=''pg-1'''` + "\n"
	out, changed, _ := addDBNameToPrimaryConninfo(conf, "repmgr")
	if !changed {
		t.Fatalf("expected a change (the dbname= substring is inside options=, not a real keyword):\n%s", out)
	}
	if !strings.Contains(out, "dbname=''repmgr''") {
		t.Errorf("dbname not appended:\n%s", out)
	}
}

// A malformed line (no matching quote pair) is a distinct, log-worthy case from
// "dbname already present" -- both are ok=false, but only one means this parser does
// not recognize a line shape repmgr actually wrote.
func TestAddDBNameToPrimaryConninfoReportsMalformedLine(t *testing.T) {
	conf := "primary_conninfo = no-quotes-here\n"
	out, changed, malformed := addDBNameToPrimaryConninfo(conf, "repmgr")
	if changed {
		t.Errorf("must not touch a malformed line:\n%s", out)
	}
	if !malformed {
		t.Error("expected malformed=true for a line with no matching quote pair")
	}
	if out != conf {
		t.Error("content must be byte-identical when left untouched")
	}
}

func TestAddDBNameToPrimaryConninfoAlreadyPresentIsNotMalformed(t *testing.T) {
	conf := `primary_conninfo = 'host=''pg-0.h'' port=5432 user=repmgr dbname=''repmgr'''` + "\n"
	_, changed, malformed := addDBNameToPrimaryConninfo(conf, "repmgr")
	if changed {
		t.Error("must not touch a line that already has dbname")
	}
	if malformed {
		t.Error("dbname already present is benign, not malformed")
	}
}

func TestEnsurePrimaryConninfoDBNameWarnsOnMalformedLine(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "postgresql.auto.conf")
	if err := os.WriteFile(path, []byte("primary_conninfo = no-quotes-here\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	changed, err := EnsurePrimaryConninfoDBName(path, "repmgr")
	if changed {
		t.Error("must not report a change for a malformed line")
	}
	if err == nil {
		t.Fatal("expected an error a caller can log for a malformed line")
	}
}

func TestEnsurePrimaryConninfoDBName(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "postgresql.auto.conf")
	if err := os.WriteFile(path, []byte(liveConninfoLine+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	changed, err := EnsurePrimaryConninfoDBName(path, "repmgr")
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("expected a change")
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "dbname=''repmgr''") {
		t.Errorf("file not updated:\n%s", b)
	}

	// Idempotent: a second call on the now-patched file is a no-op.
	changed, err = EnsurePrimaryConninfoDBName(path, "repmgr")
	if err != nil {
		t.Fatal(err)
	}
	if changed {
		t.Error("second call must be a no-op")
	}
}

func TestEnsurePrimaryConninfoDBNameMissingFile(t *testing.T) {
	_, err := EnsurePrimaryConninfoDBName(filepath.Join(t.TempDir(), "nope.conf"), "repmgr")
	if err == nil {
		t.Fatal("expected an error for a missing file")
	}
}

// #298 review: an EMPTY primary_conninfo -- the two-single-quote SQL literal -- is a SETTING
// ("do not stream"), not an empty slot to fill in. Appending dbname to it produced a non-empty
// conninfo carrying no host/port/user, so
// libpq fell back to the local unix socket and the standby's walreceiver dialed its own
// postmaster -- and changed=true made the Follow branch reload it. Reachable after boot, since
// RemoveRecoveryConfig only runs as a one-time preflight: an operator pausing replication with
// an ALTER SYSTEM setting it empty had it silently un-paused into a self-connect loop,
// permanently (hasDBNameKeyword matched afterwards, so the line was never revisited).
func TestAddDBNameToPrimaryConninfoLeavesAnEmptyValueAlone(t *testing.T) {
	for _, conf := range []string{
		"primary_conninfo = ''\n",
		"primary_conninfo = '   '\n",
		"# Do not edit this file manually!\nprimary_conninfo = ''\n",
	} {
		out, changed, malformed := addDBNameToPrimaryConninfo(conf, "repmgr")
		if changed {
			t.Errorf("an empty primary_conninfo must not be patched, got:\n%s", out)
		}
		if malformed {
			t.Errorf("an empty primary_conninfo is a valid setting, not a malformed line: %q", conf)
		}
		if out != conf {
			t.Errorf("content must be returned byte-for-byte:\nwant %q\ngot  %q", conf, out)
		}
	}
}

// #298 review: postgresql.auto.conf's primary_conninfo is not the agent's own passwordless
// value -- repmgr's repmgr.conf conninfo carries `password=${REPMGR_PASSWORD}`, and an operator
// can put one there by hand with ALTER SYSTEM -- so the migration's log lines must not print it.
func TestRedactConninfo(t *testing.T) {
	cases := []struct{ name, in, want string }{
		{"bare", "host=pg-0 password=s3cr3t user=repmgr", "host=pg-0 password=[redacted] user=repmgr"},
		{"quoted with a space", "host=pg-0 password='two words' user=repmgr", "host=pg-0 password=[redacted] user=repmgr"},
		{"spaced keyword", "host=pg-0 password = s3cr3t", "host=pg-0 password=[redacted]"},
		{"upper case", "PASSWORD=s3cr3t host=pg-0", "password=[redacted] host=pg-0"},
		{"trailing", "host=pg-0 password=s3cr3t", "host=pg-0 password=[redacted]"},
		{"none", "host=pg-0 port=5432 user=repmgr", "host=pg-0 port=5432 user=repmgr"},
		// sslpassword is libpq's own keyword for the client key's passphrase, and `\bpassword`
		// cannot match inside it -- the `l` before the `p` is a word character, so there is no
		// boundary. Without an explicit alternative it was printed verbatim (#298 review).
		{"sslpassword", "host=pg-0 sslpassword=s3cr3t", "host=pg-0 sslpassword=[redacted]"},
		{"both", "sslpassword=a password=b", "sslpassword=[redacted] password=[redacted]"},
		// passfile names a PATH, not a secret, and stays readable: it is the single most useful
		// thing in this log line when the upstream refuses the connection.
		{"passfile is not a password", "host=pg-0 passfile=/var/lib/postgresql/.pgpass", "host=pg-0 passfile=/var/lib/postgresql/.pgpass"},
		// application_name=...password... must not be mangled: the keyword is matched on a word
		// boundary, not as a substring.
		{"lookalike keyword", "host=pg-0 application_name=passwordy", "host=pg-0 application_name=passwordy"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := RedactConninfo(c.in); got != c.want {
				t.Errorf("RedactConninfo(%q) = %q, want %q", c.in, got, c.want)
			}
		})
	}
}
